DATA SETPRIMAANALFA;
	INPUT REGIAO SETOR ANALFABETISMO;
	CARDS;
	SP 2.0 17.5
	RJ 2.5 18.5
	BE 2.9 19.5
	BH 3.3 22.2
	SA 4.1 26.5
	PO 4.3 16.6
	RE 7.0 36.6
	FO 12  38.3
	; 


TITLE 'DIAGRAMA DE DISPERSÃO';
PROC PLOT;
	PLOT SETOR*ANALFABETISMO;

TITLE 'COEFICIENTE DE CORRELAÇÃO';
PROC CORR ;
	VAR SETOR ANALFABETISMO;
RUN;


TITLE 'REG.LINEAR.SIMPLES';
PROC REG;
	MODEL ANALFABETISMO = SETOR;
	OUTPUT OUT=OUT_SETPRIMAANALFA (KEEP= ANALFABETISMO  SETOR RES PRED) RESIDUAL=RES 
	PREDICTED=PRED;
	RUN;
QUIT;



